### ISSUE TITLE
v2.3.3 breaking changes

### ISSUE THREAD

**Issue by charconstpointer** [jackc/pgproto3#35]
any reason v2.3.3 includes breaking API changes and is not a major release?

**Comment by jackc** [comment]
It was a security fix.

**Comment by dan-j** [comment]
Also running into this issue with transitive dependencies.. `func (src *ErrorResponse) Encode(dst []byte) []byte` is now returning an error in addition to `[]byte`. 

If you don't want to cut a new major version, would it not be better to panic instead of changing the signature?

**Comment by jackc** [comment]
🤷 There were no perfect solutions.

A major release was infeasible (especially since this repo is already a major release behind, the current release is part of pgx v5). It causes a lot of churn and leaves everyone who didn't upgrade vulnerable.

A panic was considered, but that only changes the vulnerability to a DoS. A `WithError` method could be added, but that still leaves all existing code vulnerable.

The signature change is unfortunate, but it does force the issue to be resolved properly.
